version: '2.0'

networks:
  rede_wordpress:

volumes:
  wordpress_vol:
  mysql_vol:

services:
  wordpress:
    container_name: wordpress
    image: wordpress:5.9.3
    networks:
      - rede_wordpress
    volumes:
      - wordpress_vol:/var/www/html
    ports:
      - 8080:80
    env_file:
      - wordpress.env

  mysql:
    container_name: banco_mysql
    image: mysql:8.0
    networks:
      - rede_wordpress
    volumes:
      - mysql_vol:/var/lib/mysql
    env_file:
      - mysql.env

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    networks:
      - rede_wordpress
    ports:
      - 8081:80
    environment:
      PMA_ARBITRARY: mysql-service
      PMA_HOST: banco_mysql
      PMA_PORT: 3306
