version: '2.0'

networks:
  rede_wordpress:

volumes:
  mysql_vol:

services:
  wordpress:
    container_name: wordpress
    image: wordpress:6.1.1
    networks:
      - rede_wordpress
    volumes:
      #Apontar para pasta vazia onde ficará arquivos wordpress ou então apontar para pasta que já contém arquivos de um site existente
      - path_to_files_wordpress:/var/www/html
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: banco_mysql
    env_file:
      - wordpress.env

  mysql:
    container_name: banco_mysql
    image: mysql:8.0
    networks:
      - rede_wordpress
    volumes:
      - mysql_vol:/var/lib/mysql #Nome do volume do MySQL para armazenamento dos dados do banco de dados
    env_file:
      - mysql.env

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    networks:
      - rede_wordpress
    ports:
      - 8081:80
    environment:
      PMA_ARBITRARY: banco_mysql
      PMA_HOST: banco_mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 30000000 #delimita tamanho de arquivo que pode ser feito upload
